avi:
  enabled: true
  n_sigmas: 5
device: cuda
model:
  occlude_padding: false
  padding_mode: constant
  spatial_unet_activation: relu
  spatial_unet_depth: 3
  spatial_unet_feature_mode: repeat
  spatial_unet_first_conv_channels: 32
  spatial_unet_kernel_size: 3
  spatial_unet_n_conv_layers: 3
  spatial_unet_padding: true
  spatial_unet_readout_kernel_size: 1
  temporal_denoiser_activation: relu
  temporal_denoiser_conv_channels: 32
  temporal_denoiser_hidden_dense_layer_dims:
  - 32
  - 32
  temporal_denoiser_kernel_size: 5
  temporal_denoiser_n_conv_layers: 3
  type: spatial-unet-2d-temporal-denoiser
  use_attention: false
  use_layer_norm: true
  use_padding: false
