avi:
  enabled: true
  sigma_range:
  - 0
  - 5
device: cuda
model:
  occlude_padding: false
  padding_mode: reflect
  spatial_unet_activation: relu
  spatial_unet_attention: false
  spatial_unet_batch_norm: true
  spatial_unet_depth: 3
  spatial_unet_feature_mode: repeat
  spatial_unet_first_conv_channels: 32
  spatial_unet_kernel_size: 3
  spatial_unet_n_conv_layers: 3
  spatial_unet_padding: false
  spatial_unet_readout_kernel_size: 1
  temporal_denoiser_activation: relu
  temporal_denoiser_conv_channels: 32
  temporal_denoiser_hidden_dense_layer_dims:
  - 16
  temporal_denoiser_kernel_size: 5
  temporal_denoiser_n_conv_layers: 2
  type: spatial-unet-2d-temporal-denoiser
window:
  x0: 50
  y0: 70
  x_window: 30
  y_window: 30