datasets:
- optosynth_first_wave__1__20__50
- optosynth_first_wave__2__20__50
- optosynth_first_wave__3__20__50
- optosynth_first_wave__4__20__50
- optosynth_first_wave__5__20__50
device: cuda
log_dir: /home/jupyter/bw-data/cellmincer/logs
model:
  spatial_unet_activation: relu
  spatial_unet_batch_norm: false
  spatial_unet_depth: 3
  spatial_unet_first_conv_channels: 32
  spatial_unet_kernel_size: 3
  spatial_unet_n_conv_layers: 3
  spatial_unet_padding: true
  spatial_unet_readout_kernel_size: 1
  temporal_denoiser_activation: relu
  temporal_denoiser_conv_channels: 32
  temporal_denoiser_hidden_dense_layer_dims:
  - 32
  - 32
  temporal_denoiser_kernel_size: 5
  temporal_denoiser_n_conv_layers: 3
  type: spatial-unet-2d-temporal-denoiser
  use_attention: false
  use_global_features: true
  use_layer_norm: false
  use_padding: false
name: optosynth
root_data_dir: /home/jupyter/bw-data/cellmincer/data
root_denoise_dir: /home/jupyter/bw-data/cellmincer/denoise
root_model_dir: /home/jupyter/bw-data/cellmincer/models
state_index: 0
write_avi: true
