bfgs_kwargs:
  history_size: 100
  line_search_fn: strong_wolfe
  lr: 0.1
  max_iter: 100
  tolerance_change: 1.0e-09
  tolerance_grad: 1.0e-07
datasets:
- movie: /home/jupyter/bw-data/miller-ephys/standard_imaging/id_170802_cell_3/cell_3_1_MMStack_Pos0.ome.tif
  name: cell_3_1_MMStack_Pos0
  order: tyx
  params:
    n_frames_per_segment: 5000
    n_segments: 1
    sampling_rate: 500
- movie: /home/jupyter/bw-data/miller-ephys/standard_imaging/id_170802_cell_3/cell_3_2_MMStack_Pos0.ome.tif
  name: cell_3_2_MMStack_Pos0
  order: tyx
  params:
    n_frames_per_segment: 5000
    n_segments: 1
    sampling_rate: 500
- movie: /home/jupyter/bw-data/miller-ephys/standard_imaging/id_170816_cell_1/std_1_MMStack_Pos0.ome.tif
  name: std_1_MMStack_Pos0
  order: tyx
  params:
    n_frames_per_segment: 5000
    n_segments: 1
    sampling_rate: 500
- movie: /home/jupyter/bw-data/miller-ephys/standard_imaging/id_170816_cell_1/std_2_MMStack_Pos0.ome.tif
  name: std_2_MMStack_Pos0
  order: tyx
  params:
    n_frames_per_segment: 5000
    n_segments: 1
    sampling_rate: 500
- movie: /home/jupyter/bw-data/miller-ephys/standard_imaging/id_170816_cell_1/std_3_MMStack_Pos0.ome.tif
  name: std_3_MMStack_Pos0
  order: tyx
  params:
    n_frames_per_segment: 5000
    n_segments: 1
    sampling_rate: 500
dejitter:
  detrending_method: stft
  detrending_order: 3
  ignore_first_n_frames: 100
  show_diagnostic_plots: false
  stft_lp_cutoff: 80.0
  stft_lp_slope: 0.25
  stft_noverlap: 64
  stft_nperseg: 256
detrend:
  init_unc_decay_rate: 1.0
  max_iters_per_segment: 3
  plot_segments: true
  poly_order: 0
  trend_model: polynomial
device: cuda
log_dir: /home/jupyter/bw-data/cellmincer/logs
noise_estimation:
  n_bootstrap: 500
  plot_example: false
  plot_subsample: 1000
  stationarity_window: 10
root_data_dir: /home/jupyter/bw-data/cellmincer/data
trim:
  n_frames_fit_left: 50
  n_frames_fit_right: 0
  n_frames_stim: 900
  trim_left: 50
  trim_right: 0
