bfgs:
  history_size: 100
  line_search_fn: strong_wolfe
  lr: 0.1
  max_iter: 100
  tolerance_change: 1.0e-09
  tolerance_grad: 1.0e-07
dejitter:
  enabled: false
detrend:
  fit_enabled: true
  init_unc_decay_rate: 1.0
  max_iters_per_segment: 3
  plot_segments: true
  poly_order: 1
  trend_model: polynomial
device: cuda
ignore_first_n_frames: 0
noise_estimation:
  n_bootstrap: 500
  plot_example: true
  plot_subsample: 1000
  stationarity_window: 10
trim:
  n_frames_fit_left: 100
  n_frames_fit_right: 100
  trim_left: 0
  trim_right: 0
