bfgs:
  history_size: 100
  line_search_fn: strong_wolfe
  lr: 0.1
  max_iter: 100
  tolerance_change: 1.0e-09
  tolerance_grad: 1.0e-07
dejitter:
  enabled: false
detrend:
  enabled: false
device: cuda
log_dir: /home/jupyter/bw-data/cellmincer/logs
noise_estimation:
  n_bootstrap: 500
  plot_example: true
  plot_subsample: 1000
  stationarity_window: 10
trim:
  n_frames_fit_left: 50
  n_frames_fit_right: 0
  trim_left: 0
  trim_right: 0
