bfgs_kwargs:
  history_size: 100
  line_search_fn: strong_wolfe
  lr: 0.1
  max_iter: 100
  tolerance_change: 1.0e-09
  tolerance_grad: 1.0e-07
datasets:
- movie: /home/jupyter/bw-data/sami-optopatch/D1_FOV3_W2_at135105.bin
  name: D1_FOV3_W2_at135105
  order: tyx
  params:
    height: 180
    n_frames: 7499
    n_frames_per_segment: 750
    n_segments: 10
    sampling_rate: 500
    width: 512
- movie: /home/jupyter/bw-data/sami-optopatch/D4_FOV2_W2_at171603.bin
  name: D4_FOV2_W2_at171603
  order: tyx
  params:
    height: 180
    n_frames: 7499
    n_frames_per_segment: 750
    n_segments: 10
    sampling_rate: 500
    width: 512
- movie: /home/jupyter/bw-data/sami-optopatch/D4_FOV3_W2_at172029.bin
  name: D4_FOV3_W2_at172029
  order: tyx
  params:
    height: 180
    n_frames: 7499
    n_frames_per_segment: 750
    n_segments: 10
    sampling_rate: 500
    width: 512
- movie: /home/jupyter/bw-data/sami-optopatch/E3_FOV1_W2_at155440.bin
  name: E3_FOV1_W2_at155440
  order: tyx
  params:
    height: 180
    n_frames: 7499
    n_frames_per_segment: 750
    n_segments: 10
    sampling_rate: 500
    width: 512
- movie: /home/jupyter/bw-data/sami-optopatch/F1_FOV2_W1_at143005.bin
  name: F1_FOV2_W1_at143005
  order: tyx
  params:
    height: 180
    n_frames: 7499
    n_frames_per_segment: 750
    n_segments: 10
    sampling_rate: 500
    width: 512
dejitter:
  detrending_method: stft
  detrending_order: 3
  ignore_first_n_frames: 100
  show_diagnostic_plots: false
  stft_lp_cutoff: 80.0
  stft_lp_slope: 0.25
  stft_noverlap: 64
  stft_nperseg: 256
detrend:
  init_unc_decay_rate: 1.0
  max_iters_per_segment: 3
  plot_segments: false
  poly_order: 3
  trend_model: polynomial
device: cuda
log_dir: /home/jupyter/bw-data/cellmincer/logs
noise_estimation:
  n_bootstrap: 500
  plot_example: false
  plot_subsample: 1000
  stationarity_window: 10
root_data_dir: /home/jupyter/bw-data/cellmincer/data
trim:
  n_frames_fit_left: 150
  n_frames_fit_right: 150
  n_frames_stim: 250
  trim_left: 100
  trim_right: 50
