insight:
  enabled: false
  evaluate_every: 500
  peak: 65535
model:
  occlude_padding: true
  padding_mode: reflect
  spatial_unet_activation: relu
  spatial_unet_attention: false
  spatial_unet_batch_norm: true
  spatial_unet_depth: 3
  spatial_unet_feature_mode: repeat
  spatial_unet_first_conv_channels: 64
  spatial_unet_kernel_size: 3
  spatial_unet_n_conv_layers: 3
  spatial_unet_padding: false
  spatial_unet_readout_kernel_size: 1
  temporal_denoiser_activation: relu
  temporal_denoiser_conv_channels: 32
  temporal_denoiser_hidden_dense_layer_dims:
  - 32
  temporal_denoiser_kernel_size: 5
  temporal_denoiser_n_conv_layers: 3
  type: spatial-unet-2d-temporal-denoiser
neptune:
  api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI0YzBlMThhNS05MzI0LTRhZDEtODIzYy02ZDg0YWMzMzgwNDIifQ==
  enabled: false
  project: cellarium/CELLMINCER
  tags:
  - gpu_test
train:
  log_every: 100
  loss_type: lp
  lr_params:
    max: 0.0001
    min: 0
    type: cosine-annealing-warmup
    warmup: 0.1
  n_batch: 10
  n_iters: 50000
  norm_p: 2
  occlusion_prob: 0.2
  occlusion_radius: 0
  occlusion_strategy: random
  optim_params:
    betas:
    - 0.9
    - 0.999
    type: adam
    weight_decay: 0.1
  output_min_size_hi: 64
  output_min_size_lo: 32
  t_tandem: 1
