device: cuda
insight:
  enabled: false
  evaluate_every: 500
  peak: 65535
model:
  spatial_unet_activation: relu
  spatial_unet_batch_norm: false
  spatial_unet_depth: 3
  spatial_unet_first_conv_channels: 32
  spatial_unet_kernel_size: 3
  spatial_unet_n_conv_layers: 3
  spatial_unet_padding: true
  spatial_unet_readout_kernel_size: 1
  temporal_denoiser_activation: relu
  temporal_denoiser_conv_channels: 32
  temporal_denoiser_hidden_dense_layer_dims:
  - 32
  - 32
  temporal_denoiser_kernel_size: 5
  temporal_denoiser_n_conv_layers: 3
  type: spatial-unet-2d-temporal-denoiser
  use_attention: false
  use_global_features: true
  use_layer_norm: false
  use_padding: false
neptune:
  api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI0YzBlMThhNS05MzI0LTRhZDEtODIzYy02ZDg0YWMzMzgwNDIifQ==
  enabled: false
  name: test-cosine
  project: cellarium/CELLMINCER
  tags:
  - test
train:
  checkpoint_every: 10000
  checkpoint_path: /home/jupyter/bw-data/cellmincer/models/new-cosine-anneal/checkpoint.tar.gz
  continuity_reg_strength: 1.0
  enable_continuity_reg: false
  log_every: 100
  loss_type: lp
  lr_params:
    max: 0.001
    min: 0
    type: cosine-annealing-warmup
    warmup: 0.0
  n_batch_per_loop: 20
  n_batch_validation: 10
  n_frames_validation: 200
  n_iters: 60000
  n_loop: 1
  noise_threshold_to_std: 0.05
  norm_p: 0
  occlusion_prob: 0.05
  occlusion_radius: 0
  occlusion_strategy: random
  optim_params:
    betas:
    - 0.9
    - 0.999
    type: adam
    weight_decay: 0.1
  output_min_size_hi: 64
  output_min_size_lo: 32
  reg_func: clamped_linear
  t_tandem: 0
  validate_every: 500
